DELETE http://localhost:3003/api/comments/66bdf09069e9446b1e933846
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inlhc2g4OTY5IiwiaWQiOiI2NjhjYzY0Y2MxM2Q4NDQyZGI4ZGI2ZDEiLCJpYXQiOjE3MjA1MDg3MDR9.2y1a2iMgoQSj9YfOhCiqIVfaynAF-Iuw_73ira26-SI